# AUTO-GENERATED FILE — DO NOT EDIT

LOG_SUBSYSTEMS ={
        0: 'LOGGER',
        1: 'COMMAND',
        2: 'SERVO',
        3: 'MAGNETOMETER',
        4: 'CURRENT',
        5: 'USER_INTERFACE',
        6: 'SYSTEM',
}

LOG_LEVELS ={
        0: 'ERROR',
        1: 'EVENT',
        2: 'DATA',
        3: 'TRACE',
}

LOG_MESSAGES = {
    1: {
        'name': 'LOG_COMMAND_ERROR_FALSE_ALARM',
        'subsystem': 'COMMAND',
        'level': 'ERROR',
        'args': [],
        'format': "Error command triggered!",
    },
    2: {
        'name': 'LOG_COMMAND_ERROR_RECEIVER_BUFFER_OVERFLOW',
        'subsystem': 'COMMAND',
        'level': 'ERROR',
        'args': [],
        'format': "Receiver buffer overflow",
    },
    3: {
        'name': 'LOG_COMMAND_ERROR_RECEIVER_ERROR_CODE',
        'subsystem': 'COMMAND',
        'level': 'ERROR',
        'args': ['u8'],
        'format': "Receiver got error from handler: code {0}",
    },
    4: {
        'name': 'LOG_COMMAND_ERROR_RECEIVER_INITIALIZATION_FAILED',
        'subsystem': 'COMMAND',
        'level': 'ERROR',
        'args': [],
        'format': "Receiver initialization failed",
    },
    5: {
        'name': 'LOG_COMMAND_EVENT_COMMAND_EXECUTED',
        'subsystem': 'COMMAND',
        'level': 'EVENT',
        'args': [],
        'format': "Command received and executed",
    },
    6: {
        'name': 'LOG_COMMAND_EVENT_PING',
        'subsystem': 'COMMAND',
        'level': 'EVENT',
        'args': [],
        'format': "Pingback",
    },
    7: {
        'name': 'LOG_COMMAND_EVENT_RECEIVER_TIMEOUT',
        'subsystem': 'COMMAND',
        'level': 'EVENT',
        'args': [],
        'format': "Receiver suffered a timeout, command buffer is reset",
    },
    8: {
        'name': 'LOG_COMMAND_TRACE_COMMAND_HANDLER_INITIALIZED',
        'subsystem': 'COMMAND',
        'level': 'TRACE',
        'args': [],
        'format': "Command Handler initialized",
    },
    9: {
        'name': 'LOG_COMMAND_TRACE_RECEIVER_INITIALIZED',
        'subsystem': 'COMMAND',
        'level': 'TRACE',
        'args': [],
        'format': "Receiver initialized",
    },
    10: {
        'name': 'LOG_CURRENT_DATA_READING',
        'subsystem': 'CURRENT',
        'level': 'DATA',
        'args': ['i32'],
        'format': "Current sensor reading: {0} uA",
    },
    11: {
        'name': 'LOG_CURRENT_ERROR_INITIALIZATION_FAILED',
        'subsystem': 'CURRENT',
        'level': 'ERROR',
        'args': [],
        'format': "Initialization failed, no ADC parameters",
    },
    12: {
        'name': 'LOG_CURRENT_ERROR_INITIALIZATION_FAILED_ADC',
        'subsystem': 'CURRENT',
        'level': 'ERROR',
        'args': [],
        'format': "No pin assigned to ADC",
    },
    13: {
        'name': 'LOG_CURRENT_EVENT_NO_CURRENT',
        'subsystem': 'CURRENT',
        'level': 'EVENT',
        'args': [],
        'format': "Sensor detected no current",
    },
    14: {
        'name': 'LOG_CURRENT_TRACE_INITIALIZATION',
        'subsystem': 'CURRENT',
        'level': 'TRACE',
        'args': [],
        'format': "Current sensor initialized",
    },
    15: {
        'name': 'LOG_CURRENT_TRACE_RAW_READING',
        'subsystem': 'CURRENT',
        'level': 'TRACE',
        'args': ['i32'],
        'format': "Raw ADC reading: {0} ",
    },
    16: {
        'name': 'LOG_LOGGER_ERROR_BUFFER_OVERFLOW',
        'subsystem': 'LOGGER',
        'level': 'ERROR',
        'args': [],
        'format': "Message buffer overflow, too many messages were accumulated",
    },
    17: {
        'name': 'LOG_LOGGER_TRACE_LOGGER_INITIALIZED',
        'subsystem': 'LOGGER',
        'level': 'TRACE',
        'args': [],
        'format': "Logger Initialized",
    },
    18: {
        'name': 'LOG_LOGGER_TRACE_TRANSMISSION_BYTES',
        'subsystem': 'LOGGER',
        'level': 'TRACE',
        'args': ['u16'],
        'format': "Bytes sent on Logger Flush: {0}",
    },
    19: {
        'name': 'LOG_LOGGER_TRACE_TRANSMITTER_INITIALIZED',
        'subsystem': 'LOGGER',
        'level': 'TRACE',
        'args': [],
        'format': "Logger Initialized",
    },
    20: {
        'name': 'LOG_MAGNETOMETER_DATA_READING',
        'subsystem': 'MAGNETOMETER',
        'level': 'DATA',
        'args': ['i16'],
        'format': "Magnetometer direction: {0} deg",
    },
    21: {
        'name': 'LOG_MAGNETOMETER_ERROR_INITIALIZATION_FAILED',
        'subsystem': 'MAGNETOMETER',
        'level': 'ERROR',
        'args': [],
        'format': "Magnetometer initialization failed",
    },
    22: {
        'name': 'LOG_MAGNETOMETER_EVENT_NEW_READ_FAILED',
        'subsystem': 'MAGNETOMETER',
        'level': 'EVENT',
        'args': [],
        'format': "New read attempt failed",
    },
    23: {
        'name': 'LOG_MAGNETOMETER_TRACE_INITIALIZATION',
        'subsystem': 'MAGNETOMETER',
        'level': 'TRACE',
        'args': [],
        'format': "Magnetometer initialized",
    },
    24: {
        'name': 'LOG_SERVO_DATA_DIRECTION',
        'subsystem': 'SERVO',
        'level': 'DATA',
        'args': ['i16'],
        'format': "Servo arm: {0} deg",
    },
    25: {
        'name': 'LOG_SERVO_DATA_REFERENCE',
        'subsystem': 'SERVO',
        'level': 'DATA',
        'args': ['i16'],
        'format': "Yaw Controller Reference: {0} deg",
    },
    26: {
        'name': 'LOG_SERVO_TRACE_INITIALIZED',
        'subsystem': 'SERVO',
        'level': 'TRACE',
        'args': [],
        'format': "Servo Initialized",
    },
    27: {
        'name': 'LOG_SYSTEM_ERROR_LOOP_TIME_EXCEEDED',
        'subsystem': 'SYSTEM',
        'level': 'ERROR',
        'args': [],
        'format': "Loop time exceeded",
    },
    28: {
        'name': 'LOG_SYSTEM_TRACE_COMMAND_HANDLER_RUNNING',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "Command Handler task running",
    },
    29: {
        'name': 'LOG_SYSTEM_TRACE_COMMAND_HANDLER_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "Command Handler task time: {0} us",
    },
    30: {
        'name': 'LOG_SYSTEM_TRACE_CURRENT_SENSOR_RUNNING',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "Current Sensor task running",
    },
    31: {
        'name': 'LOG_SYSTEM_TRACE_CURRENT_SENSOR_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "Current Sensor task time: {0} us",
    },
    32: {
        'name': 'LOG_SYSTEM_TRACE_INITIALIZED',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "System Initialized",
    },
    33: {
        'name': 'LOG_SYSTEM_TRACE_LOGGER_RUNNING',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "Logger task running",
    },
    34: {
        'name': 'LOG_SYSTEM_TRACE_LOGGER_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "Logger task time: {0} us",
    },
    35: {
        'name': 'LOG_SYSTEM_TRACE_LOOP_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "Loop time: {0} us",
    },
    36: {
        'name': 'LOG_SYSTEM_TRACE_MAGNETOMETER_RUNNING',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "Magnetometer task running",
    },
    37: {
        'name': 'LOG_SYSTEM_TRACE_MAGNETOMETER_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "Magnetometer task time: {0} us",
    },
    38: {
        'name': 'LOG_SYSTEM_TRACE_USER_INTERFACE_RUNNING',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "User Interface task running",
    },
    39: {
        'name': 'LOG_SYSTEM_TRACE_USER_INTERFACE_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "User Interface task time: {0} us",
    },
    40: {
        'name': 'LOG_SYSTEM_TRACE_YAW_CONTROLLER_RUNNING',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': [],
        'format': "Yaw Controller task running",
    },
    41: {
        'name': 'LOG_SYSTEM_TRACE_YAW_CONTROLLER_TIME',
        'subsystem': 'SYSTEM',
        'level': 'TRACE',
        'args': ['u32'],
        'format': "Yaw Controller task time: {0} us",
    },
    42: {
        'name': 'LOG_USER_INTERFACE_DATA_BUTTON_STATE',
        'subsystem': 'USER_INTERFACE',
        'level': 'DATA',
        'args': ['u8'],
        'format': "Button state: {0}",
    },
    43: {
        'name': 'LOG_USER_INTERFACE_DATA_BUZZER_STATE',
        'subsystem': 'USER_INTERFACE',
        'level': 'DATA',
        'args': ['u8'],
        'format': "Buzzer state: {0}",
    },
    44: {
        'name': 'LOG_USER_INTERFACE_DATA_LED_STATE',
        'subsystem': 'USER_INTERFACE',
        'level': 'DATA',
        'args': ['u8'],
        'format': "LED state: {0}",
    },
    45: {
        'name': 'LOG_USER_INTERFACE_ERROR_INITIALIZATION_FAILED',
        'subsystem': 'USER_INTERFACE',
        'level': 'ERROR',
        'args': [],
        'format': "User Interface initialization failed",
    },
    46: {
        'name': 'LOG_USER_INTERFACE_EVENT_BUTTON',
        'subsystem': 'USER_INTERFACE',
        'level': 'EVENT',
        'args': [],
        'format': "Button pressed",
    },
    47: {
        'name': 'LOG_USER_INTERFACE_TRACE_INITIALIZED',
        'subsystem': 'USER_INTERFACE',
        'level': 'TRACE',
        'args': [],
        'format': "User interface initialized",
    },
}
