// AUTO-GENERATED — DO NOT EDIT

#ifndef D_LOGS_IDS_H
#define D_LOGS_IDS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LOG_COMMAND_ERROR_FALSE_ALARM = 1,
    LOG_COMMAND_ERROR_RECEIVER_BUFFER_OVERFLOW = 2,
    LOG_COMMAND_ERROR_RECEIVER_ERROR_CODE = 3,
    LOG_COMMAND_ERROR_RECEIVER_INITIALIZATION_FAILED = 4,
    LOG_COMMAND_EVENT_COMMAND_EXECUTED = 5,
    LOG_COMMAND_EVENT_PING = 6,
    LOG_COMMAND_EVENT_RECEIVER_TIMEOUT = 7,
    LOG_COMMAND_TRACE_COMMAND_HANDLER_INITIALIZED = 8,
    LOG_COMMAND_TRACE_RECEIVER_INITIALIZED = 9,
    LOG_CURRENT_DATA_READING = 10,
    LOG_LOGGER_ERROR_BUFFER_OVERFLOW = 11,
    LOG_LOGGER_TRACE_LOGGER_INITIALIZED = 12,
    LOG_LOGGER_TRACE_TRANSMITTER_INITIALIZED = 13,
    LOG_MAGNETOMETER_DATA_READING = 14,
    LOG_SERVO_DATA_DIRECTION = 15,
    LOG_SERVO_DATA_REFERENCE = 16,
    LOG_SERVO_TRACE_INITIALIZED = 17,
    LOG_SYSTEM_TRACE_INITIALIZED = 18,
    LOG_SYSTEM_TRACE_LOOP_TIME = 19,
    LOG_USER_INTERFACE_EVENT_BUTTON = 20,
    LOG_MESSAGEID_COUNT
} Log_MessageId_t;

typedef enum {
    LOG_SUBSYS_LOGGER,
    LOG_SUBSYS_COMMAND,
    LOG_SUBSYS_SERVO,
    LOG_SUBSYS_MAGNETOMETER,
    LOG_SUBSYS_CURRENT,
    LOG_SUBSYS_USER_INTERFACE,
    LOG_SUBSYS_SYSTEM,
    LOG_SUBSYSTEM_COUNT
} Log_Subsystem_t;

typedef enum {
    LOG_LEVEL_ERROR,
    LOG_LEVEL_EVENT,
    LOG_LEVEL_DATA,
    LOG_LEVEL_TRACE,
    LOG_LEVEL_COUNT
} Log_Level_t;

#ifdef __cplusplus
}
#endif

#endif /* D_LOGS_IDS_H */