// AUTO-GENERATED — DO NOT EDIT

#ifndef D_LOGS_IDS_H
#define D_LOGS_IDS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LOG_COMMAND_EVENT_PING = 1,
    LOG_COMMAND_TRACE_INITIALIZED = 2,
    LOG_LOGGER_ERROR_BUFFER_OVERFLOW = 3,
    LOG_LOGGER_TRACE_INITIALIZED = 4,
    LOG_MAGNETOMETER_DATA_READING = 5,
    LOG_SERVO_DATA_DIRECTION = 6,
    LOG_SYSTEM_TRACE_INITIALIZED = 7,
    LOG_MESSAGEID_COUNT
} Log_MessageId_t;

typedef enum {
    LOG_SUBSYS_LOGGER,
    LOG_SUBSYS_COMMAND,
    LOG_SUBSYS_SERVO,
    LOG_SUBSYS_MAGNETOMETER,
    LOG_SUBSYS_CURRENT,
    LOG_SUBSYS_USER_INTERFACE,
    LOG_SUBSYS_SYSTEM,
    LOG_SUBSYSTEM_COUNT
} Log_Subsystem_t;

typedef enum {
    LOG_LEVEL_ERROR,
    LOG_LEVEL_EVENT,
    LOG_LEVEL_DATA,
    LOG_LEVEL_TRACE,
    LOG_LEVEL_COUNT
} Log_Level_t;

#ifdef __cplusplus
}
#endif

#endif /* D_LOGS_IDS_H */